# It's not worth creating a bunch of db schema info for this data which is only
# used to generate informational text.
# DO NOT let this yaml become a dumping ground for things that should be in
# the db (famous last words).  Rule of thumb: If you need to know the value
# behind the formatted text, don't put it here.

install_day: "Friday, July 3, 2026"
skill_attend_day: "Tuesday, June 30, 2026"
Temple:
  contract_deadline: "Sunday, March 8, 2026"
  schedule: ["Sunday, Feb 22, 2026: Submissions Due",
             "Sunday, March 8, 2026: Signed Contracts Due",
             "Friday, March 20, 2026: Check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!"]
Creativity:
  contract_deadline: "Sunday, March 22, 2026"
  schedule: ["Sunday, March 8, 2026: Submissions Due",
             "Sunday, March 22, 2026: Signed Contracts Due",
             "Sunday, March 29, 2026: First check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!",
             "Friday, July 24, 2026: Firefly documentation due",
             "Friday, July 31, 2026: Second check cut and sent"]
Creativity Round 2:
  contract_deadline: "Sunday, April 26, 2026"
  schedule: ["Sunday, April 12, 2026: Submissions Due",
             "Sunday, April 26, 2026: Signed Contracts Due",
             "Sunday, May 24, 2026: First check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!",
             "Friday, July 24, 2026: Firefly documentation due",
             "Friday, July 31, 2026: Second check cut and sent"]
Legacy:
  contract_deadline: "Sunday, May 17, 2026"
  schedule: ["Sunday, May 3, 2026: Submissions Due",
             "Sunday, May 17, 2026: Signed Contracts Due",
             "Sunday, May 24, 2026: Check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!"]
Burner Exchange:
  contract_deadline: "Sunday, May 17, 2026"
  schedule: ["Sunday, May 3, 2026: Submissions Due",
             "Sunday, May 17, 2026: Signed Contracts Due",
             "Sunday, May 24, 2026: Check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!"]
Moonshot (disabled):
  contract_deadline: "10 days after notification of Grant"
  schedule: ["Wednesday, June 29 - Monday, July 4, 2022: Firefly!",
             "Friday, July 22, 2022: Firefly documentation due"]
Skillshare (disabled):
  contract_deadline: "Friday, June 3, 2022"
  schedule: ["Friday, May 14, 2022: Signed Contracts Due",
             "Monday, May 16, 2022: Check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!"]
TEST GRANT:
  contract_deadline: "Sunday, March 29, 2026"
  schedule: ["Sunday, March 8, 2026: Submissions Due",
             "Sunday, March 29, 2026: Signed Contracts Due",
             "Sunday, April 5, 2026: First check cut and sent",
             "Tuesday, June 30 - Sunday, July 5, 2026: Firefly!",
             "Friday, July 24, 2026: Firefly documentation due",
             "Friday, Aug 7, 2026: Second check cut and sent"]
